# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageChat' do
  use_frameworks!
pod 'AFNetworking', '~> 3.0'
pod 'Masonry', '~> 1.0.2'
pod 'CocoaLumberjack', '~> 3.0.0'



  target 'ImageChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
